### PR TITLE
XRE-16605 Add import and create named key APIs for SecApi

### PR DESCRIPTION
**Pull request by yashaswini-rk**

### CODE REVIEW

**Comment by yashaswini-rk** [comment]
@pwielders Could you please review this.

**Comment by pwielders** [comment]
@sebaszm was this funtionality not available?

**Comment by yashaswini-rk** [comment]
@sebaszm and @pwielders  , As per our previous discussion , have made the following changes: 
1.Include the ImportNamedKey API logic  as part of the Import API
2.Add the CreateKey API

Could you pls review .Thanks.

**Review by pwielders — CHANGES_REQUESTED** [review]
I (and I assume @sebaszm agrees) where not expecting to see changes on the standard interfaces. These are good for most deployments. The exepctation is that you would "add" a layer on top of this layer for naming ID's. Create a dictionary where you could do a name -> id translation. This way the basic interface stays simple (we love simple) and by adding a new layer, if you need it, you add functionality.
Now all our apps out there are facing interface changes that we need to enforce without any added value, these are breaking interfaces.

**Comment by yashaswini-rk** [comment]
@pwielders 
If the main crypto interfaces should not be modified , can we introduce these APIs as another vault under the SecAPI backend( Something like VaultRDK).So we could add the API ,  ImportNamedKey()  to be mapped to vault_import inside this VaultRDK without bringing in any modifications in the ICryptography or IVault interface.
The only change would be addition of another cryptography vault id for this , like CRYPTOGRAPHY_VAULT_RDK.

But for the other API , i,e CreateKey ..since this a new API not previously part of the IVault interface , How could we add this without modifying the IVault interface ?

**Comment by pwielders** [comment]
@yashaswini-rk as discussed in our call, I suggest to create a layer, not part of this pull request, that realizes the key name to id mapping (something we do using our Dictionary plugin), creating a dedicated vault will thinks only more complex. Just move it up.

The CreateKey (@sebaszm ) was indeed an omission which I think can be a usefull addition. @sebaszm to confirm and to review that interface.

**Comment by yashaswini-rk** [comment]
Closing this as these changes trying to bring up as  IPersistent interface

**Pull request closed without merging**
